apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: everyrow-mcp
  namespace: everyrow-mcp
spec:
  parentRefs:
  - name: shared-tls-gateway
    namespace: cert-manager
  hostnames:
  - {{ .Values.httproute.host }}
  rules:
  - backendRefs:
    - name: everyrow-mcp
      namespace: everyrow-mcp
      port: {{ .Values.service.port }}
