#ENC[AES256_GCM,data:1qvGrNOeiVigrYL3Q7DgGx+4VJp0fj56rcXWChVLAfvHVnEHK/uwrIqBuZBNYqof,iv:IM0hJ7dgwD+y2ZLM+Qk/EckedDUEXi34dRESFWp8C0E=,tag:nAydLpdscuh+9kwjDTF/lw==,type:comment]
#ENC[AES256_GCM,data:8pJ6mvIK/olfB+UnrMtUVM9BtWMEDV0NzEmLRRnI/Uy0rPVWe9GmPxx2rIz7lK/7Aae4jkZArV5rl9w=,iv:QOXXt6SQclRo3jYlIVkwxndyR+0x+h0ZaJ2KmxqhlKg=,tag:gg5BBtz6dAXazasaJhPPkA==,type:comment]
#
#ENC[AES256_GCM,data:kyjar187QZ9TfKMBL1flSbeMdcmmkwVFIyywq2Puiz+zRUTMcl833uD2nr8mgw==,iv:U3frSmYAhSmhmeT4OHPkZSuh2qWNaT2JwKxPptcRGGs=,tag:5oLStR7cZmfw/+ADYx+t0Q==,type:comment]
#ENC[AES256_GCM,data:BCaC1l33I3GK0H2MPg/TxEfGEG2gaDuAKNeU9MBir2PfbBeWZGfh3yLnL369CWbmq0CMbI4l3whRxfTgdQ==,iv:8cVXEqSaQyiZlFzy1pkoXM0kr5/YHz4SVXKwTFGpr6g=,tag:15kV43JfurvpKUAP8lQYCw==,type:comment]
#ENC[AES256_GCM,data:Yj7vghEZt1TxKZnpzhezlaxlY9ZvMCjB5aVW7alHpQerDqf9xN20Q0JfhwXMEbzNOvStENafNu4=,iv:2Aby0h79KFPztNnXgih3DGVj4PqJFfGdZER9AoSD6xs=,tag:bLs9GZBUObVNAyUROXiuSg==,type:comment]
#
#ENC[AES256_GCM,data:uy9KBMY/INm6NImm0Z21tGq5rLUDfxszlnQFQW4e8YT0KjhJdQ2GnZYX7g23GtiMX2qCvtv8oYpzT3b+S41kWujm1uk9FlKgNGPG,iv:esC00kOVatG+OR0MhIlD8ClYG/oZyz6Fc9Gd2BszTTI=,tag:0kuacywR/FJPkqdHg6VOsA==,type:comment]
#ENC[AES256_GCM,data:Tpx6cwU52EpbZv2M/CLzAAlmd80HLJUaeYGEGLxtCJolrvuop+VNQLWgbUcMtY4E//ZWmjaQ01+tBOID50j8sUln1hg=,iv:umsGNjyNTl8f6O8WNT1Did00ixTmsf2JxftvHgkdd74=,tag:d4+CZA6q6MQmbXqeEYVlkw==,type:comment]
#ENC[AES256_GCM,data:5xllYFMerLbs21ofJqNKWKuSRfbPu6Z88v20IJO0JWLTDNx5NXMPPRnZa4TFXNfSddKMJu0g/YvoOdhvZ33U+JTqfwwwDFUU1vqRiWYqnjuV/g==,iv:Sb1KWgMVFbOS5G3e1jfj55inDLLs/J5iHU/w9M485iQ=,tag:u2NaDfoam5utoC+DjKTZEg==,type:comment]
secrets:
    data:
        SUPABASE_ANON_KEY: ENC[AES256_GCM,data:h+qJ9Be5PbPbzo/6lq6c8CqXrCxMVh6auscddMTBpR22i56J6op3U7JjvSrh4w==,iv:JK6EYNEh9FP31ZWP0anJDvP1g3OvqkmqKEXAv7hRznU=,tag:NAtyA9ZVBB6AbQFLbXZoRQ==,type:str]
        REDIS_ENCRYPTION_KEY: ENC[AES256_GCM,data:H9M679no7sspDZZelDI7GQpDwAYrbx6mWkszwC4m8Pr2dY7LA3wkWG682/o=,iv:QY3WXoFE21HbV9FnHo2V6Kb3OT02g3nYxThMI043f7w=,tag:t0JBg2zqFnZhQ0veyJp4uQ==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/varuna-400921/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-02-19T11:48:19Z"
          enc: CiQA/cVY+7sPeizMRAhuaujldllHVIcphFe4b0hCn3vihvde2f4SSQAXYxKUpCrhxAn9NiRMvikYR8Hvlb5I8FPTtpxgRF0teTaz9wyxqVg1CdhlBmuwmkRPO+xEJLwiGBacIQxX8sxUmgq0DCVRzsU=
    lastmodified: "2026-02-19T16:21:28Z"
    mac: ENC[AES256_GCM,data:ERdmweTehwWwzdvT32PXCY2t6bQHZ2CvIFwTMbY4e4CFWULOpNegtrCpnbXROVV5MUBzibHOyaGGq6lwUe35DbKXXEckyIG6O3pXHWa/L8EfJQ+bIsv091CFORO6t5QXz6Wqhp+e+glSkTNlusWeNxAhieRqOTZZmmg1cvYwOzE=,iv:ib4QgC2o9o1y3WMGv4G7LZzhu+JmMEb8RJisdHZS8d4=,tag:SYfOtPfMfA5ozrllm7qbmQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
